blockexplorer/urls.py
from django.conf.urls import url

from addresses import views as addresses_views
from blocks import views as blocks_views
from homepage import views as homepage_views
from transactions import views as transactions_views
from users import views as users_views
from wallets import views as wallets_views



urlpatterns = [
    # Logging Test
    url(r'^fail500/$', homepage_views.fail500, name='fail500'),

    # Login
    url(r'^signuup/?$', users_views.signup, name='signup'),
    url(r'^logiin/?$', users_views.user_login, name='user_login'),
    url(r'^logout/?$', users_views.logout_request, name='logout_request'),
    url(r'^confirm/(?P<verif_code>[-\w]+)/$', users_views.confirm_subscription, name='confirm_subscription'),
    url(r'^unconfirmed-email/?$', users_views.unconfirmed_email, name='unconfirmed_email'),
    url(r'^confirm-pw-reset/(?P<email_address>[-\w@.+]+)?$', users_views.confirm_pw_reset, name='confirm_pw_reset'),
    url(r'^set-password/?$', users_views.password_upsell, name='password_upsell'),
    url(r'^change-password/?$', users_views.change_password, name='change_password'),
    url(r'^forgot-password/?$', users_views.forgot_password, name='forgot_password'),
    url(r'^reset-pw/(?P<verif_code>[-\w@.+]+)?$', users_views.reset_pw, name='reset_pw'),
    url(r'^dashboard/?$', users_views.dashboard, name='dashboard'),

    # App pages
    url(r'^$', homepage_views.home, name='home'),
    url(r'^(?P<coin_symbol>[-\w]+)/address/(?P<address>[-\w]+)/$', addresses_views.address_overview, name='address_overview'),
    url(r'^(?P<coin_symbol>[-\w]+)/address/(?P<address>[-\w]+)/(?P<wallet_name>[-\w\.]+)/$', addresses_views.address_overview, name='address_overview'),
    url(r'^(?P<coin_symbol>[-\w]+)/tx/(?P<tx_hash>[-\w]+)/$', transactions_views.transaction_overview, name='transaction_overview'),
    url(r'^(?P<coin_symbol>[-\w]+)/block/(?P<block_representation>[-\w]+)/$', blocks_views.block_overview, name='block_overview'),
    url(r'^(?P<coin_symbol>[-\w]+)/xpub/(?P<pubkey>[-\w]+)/$', wallets_views.wallet_overview, name='wallet_overview_default'),
    url(r'^(?P<coin_symbol>[-\w]+)/pushtx/$', transactions_views.push_tx, name='push_tx'),
    url(r'^(?P<coin_symbol>[-\w]+)/decodetx/$', transactions_views.decode_tx, name='decode_tx'),
    url(r'^highlights/$', homepage_views.highlights, name='highlights'),
    # AJAX calls
    url(r'^(?P<coin_symbol>[-\w]+)/tx-confidence/(?P<tx_hash>[-\w]+)/$', transactions_views.poll_confidence, name='poll_confidence'),

    # Widget
    url(r'^widgets/(?P<coin_symbol>[-\w]+)/?$', addresses_views.search_widgets, name='search_widgets'),
    url(r'^show-widgets/(?P<coin_symbol>[-\w]+)/(?P<address>[-\w]+)/$', addresses_views.widgets_overview, name='widgets_overview'),
    url(r'^widget/(?P<coin_symbol>[-\w]+)/(?P<address>[-\w]+)/balance/$', addresses_views.render_balance_widget, name='render_balance_widget'),
    url(r'^widget/(?P<coin_symbol>[-\w]+)/(?P<address>[-\w]+)/received/$', addresses_views.render_received_widget, name='render_received_widget'),

    # Forwarding Pages (URL hacks)
    url(r'^widgets/$', addresses_views.widget_forwarding, name='widget_forwarding'),
    url(r'^pushtx/$', transactions_views.pushtx_forwarding, name='pushtx_forwarding'),
    url(r'^decodetx/$', transactions_views.decodetx_forwarding, name='decodetx_forwarding'),
    url(r'^latest-block/$', blocks_views.latest_block_forwarding, name='latest_block_forwarding'),
    url(r'^(?P<coin_symbol>[-\w]+)/latest-block/$', blocks_views.latest_block, name='latest_block'),
    url(r'^latest-unconfirmed-tx/$', transactions_views.latest_unconfirmed_tx_forwarding, name='latest_unconfirmed_tx_forwarding'),
    url(r'^(?P<coin_symbol>[-\w]+)/latest-unconfirmed-tx/$', transactions_views.latest_unconfirmed_tx, name='latest_unconfirmed_tx'),
    url(r'^(?P<coin_symbol>[-\w]+)/block/(?P<block_num>[\d]+)/(?P<tx_num>[\d]+)/$', blocks_views.block_ordered_tx, name='block_ordered_tx'),

    # So broad it must be last
    url(r'^(?P<coin_symbol>[-\w]+)/$', homepage_views.coin_overview, name='coin_overview')
]

homepage/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _

from blockcypher.constants import COIN_CHOICES, UNIT_CHOICES_DJANGO
from blockcypher.utils import is_valid_address, is_valid_eth_address, is_valid_hash, is_valid_block_num

from blockexplorer.walletname import is_valid_wallet_name

import re


class SearchForm(forms.Form):
    search_string = forms.CharField(
        required=True,
        min_length=1,
        max_length=128,
    )

    coin_symbol = forms.ChoiceField(
        required=False,
        choices=COIN_CHOICES,
    )

    def clean_search_string(self):
        search_string = self.cleaned_data['search_string'].strip()
        # process possible Wallet Names
        if is_valid_wallet_name(search_string):
            return search_string

        # get rid of non alphanumerics
        if search_string.lower().startswith("0x"):
            search_string = search_string[2:].lower()
        search_string = re.sub(r'[^a-zA-Z0-9]+', '', search_string)
        if is_valid_hash(search_string) or is_valid_address(search_string) or is_valid_eth_address(search_string) or is_valid_block_num(search_string):
            return search_string
        else:
            err_msg = _('Not a valid address, transaction hash, or block number')
            raise forms.ValidationError(err_msg)


class UnitChoiceForm(forms.Form):
    unit_choice = forms.ChoiceField(
        label='',
        required=True,
        choices=UNIT_CHOICES_DJANGO,
        widget=forms.Select(attrs={'onchange': 'this.form.submit()'}),
    )

users/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _


from blockcypher.constants import COIN_CHOICES


class LoginForm(forms.Form):
    email = forms.EmailField(
        label=_('Email'),
        required=True,
        widget=forms.TextInput(attrs={
            'placeholder': 'me@example.com',
            'autofocus': 'autofocus',
            'class': 'input-lg',
            }),
    )
    password = forms.CharField(
        label=_('Password'),
        required=True,
        min_length=6,
        widget=forms.PasswordInput(attrs={'class': 'input-lg'}, render_value=False)
    )

    def clean_email(self):
        email = self.cleaned_data['email']
        return email.lower().strip()


class PWResetForm(forms.Form):
    email = forms.EmailField(
        label=_('Email'),
        required=True,
        widget=forms.TextInput(attrs={
            'placeholder': 'me@example.com',
            'autofocus': 'autofocus',
            'class': 'input-lg',
            }),
    )

    def clean_email(self):
        email = self.cleaned_data['email']
        return email.lower().strip()


class RegistrationForm(forms.Form):
    email = forms.EmailField(
        label=_('Email'),
        required=True,
        max_length=100,
        widget=forms.TextInput(attrs={
            'placeholder': 'me@example.com',
            'autofocus': 'autofocus',
            'class': 'input-lg',
            }),
    )
    password = forms.CharField(
        required=True,
        label=_('Password'),
        widget=forms.PasswordInput(attrs={'class': 'input-lg'}),
        min_length=12,
    )
    password_confirm = forms.CharField(
        required=True,
        label=_('Confirm Password'),
        widget=forms.PasswordInput(attrs={'class': 'input-lg'}),
        min_length=12,
    )

    def __init__(self, *args, **kwargs):
        super(RegistrationForm, self).__init__(*args, **kwargs)

    def clean_email(self):
        return self.cleaned_data['email'].lower().strip()

    def clean(self):
        pw = self.cleaned_data.get('password')
        pwc = self.cleaned_data.get('password_confirm')
        if pw != pwc:
            err_msg = _('Those passwords did not match. Please try again.')
            raise forms.ValidationError(err_msg)
        else:
            return self.cleaned_data


class CoinSymbolForm(forms.Form):
    coin_symbol = forms.ChoiceField(
            label=_('Blockchain'),
            required=True,
            choices=COIN_CHOICES,
            widget=forms.Select(attrs={'onchange': 'this.form.submit()', 'class': 'input-lg'}),
            )


class SetPWForm(forms.Form):
    password = forms.CharField(
        required=True,
        label=_('Password'),
        widget=forms.PasswordInput(attrs={
            'class': 'input-lg',
            'autofocus': 'autofocus',
            }),
        min_length=12,
    )
    password_confirm = forms.CharField(
        required=True,
        label=_('Confirm Password'),
        widget=forms.PasswordInput(attrs={'class': 'input-lg'}),
        min_length=12,
    )

    def __init__(self, *args, **kwargs):
        super(SetPWForm, self).__init__(*args, **kwargs)

    def clean(self):
        pw = self.cleaned_data.get('password')
        pwc = self.cleaned_data.get('password_confirm')
        if pw != pwc:
            err_msg = _('Those passwords did not match. Please try again.')
            raise forms.ValidationError(err_msg)
        else:
            return self.cleaned_data


class ChangePWForm(forms.Form):

    oldpassword = forms.CharField(
            required=True,
            label=_('Current Password'),
            widget=forms.PasswordInput(attrs={
                'autocomplete': 'off',
                'autofocus': 'autofocus',
                }),
            help_text=_('Your existing password that you no longer want to use'),
    )

    newpassword = forms.CharField(
            required=True,
            label=_('New Password'),
            widget=forms.PasswordInput(attrs={'autocomplete': 'off'}),
            min_length=12,
            help_text=_('Please choose a new secure password'),
    )

    newpassword_confirm = forms.CharField(
            required=True,
            label=_('Confirm New Password'),
            widget=forms.PasswordInput(attrs={'autocomplete': 'off'}),
    )

    def __init__(self, user, *args, **kwargs):
        self.user = user
        super(ChangePWForm, self).__init__(*args, **kwargs)

    def clean_oldpassword(self):
        password = self.cleaned_data['oldpassword']
        if not self.user.check_password(password):
            raise forms.ValidationError(_('Sorry, that password is not correct'))
        return password

    def clean(self):
        if self.cleaned_data.get('newpassword') != self.cleaned_data.get('newpassword_confirm'):
            raise forms.ValidationError(_('Your new passwords did not match.  Please try again.'))
        if self.cleaned_data.get('newpassword') == self.cleaned_data.get('oldpassword'):
            raise forms.ValidationError(_('Your old password matches your new password. Your password was not changed.'))
        else:
            return self.cleaned_data

templates/balance_widget.html
{% load btc_formats %}
{% load humanize %}

<html>
  <head>
    <title></title>
    {# Bootstrap core CSS #}
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet">

    {# FontAwesome #}
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">

  </head>
  <body>

    <a target="_blank" href="{{ BASE_URL }}{% url 'address_overview' coin_symbol b58_address %}" class="btn btn-default">

      <i class="fa fa-qrcode"></i> 
      {{ b58_address }}

      <h4>
        {% satoshis_to_user_units_trimmed address_overview.final_balance 'btc' coin_symbol True 0 %}
      </h4>

      <i>
        {{ address_overview.final_n_tx|intcomma }} Transaction{{ address_overview.final_n_tx|pluralize }}
        {% if address_overview.unconfirmed_n_tx %}
          ({{ address_overview.unconfirmed_n_tx }} Unconfirmed)
        {% endif %}
      </i>

    </a>

    <p align="center">
      <a class="text-muted" href="http://www.blockcypher.com/">Powered by BlockCypher</a>
    </p>

  </body>
</html>

templates/base.html
{% load static %}
{% load i18n %}
{% load btc_formats %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <meta name="description" content="{% block meta_description %}{% endblock meta_description %}">
    <meta name="author" content="">

    <link rel="icon" type="image/png" href="{% static "img/favicon-192x192.png" %}" sizes="192x192">
    <link rel="icon" type="image/png" href="{% static "img/favicon-160x160.png" %}" sizes="160x160">
    <link rel="icon" type="image/png" href="{% static "img/favicon-96x96.png" %}" sizes="96x96">
    <link rel="icon" type="image/png" href="{% static "img/favicon-16x16.png" %}" sizes="16x16">
    <link rel="icon" type="image/png" href="{% static "img/favicon-32x32.png" %}" sizes="32x32">

    <title>
      {% block title %}
        {% trans "Block Explorer for Bitcoin, Ethereum, Litecoin and More" %}
      {% endblock %}
      | BlockCypher
    </title>

    {# Webfonts #}
    <link href='//fonts.googleapis.com/css?family=Raleway:300' rel='stylesheet' type='text/css'>

    {# Bootstrap core CSS #}
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet">

    {# FontAwesome #}
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">

    {# Custom css #}
    <link href="{% static "css/custom.css" %}" rel="stylesheet">

    {% block extra_head %}{% endblock extra_head %}

  </head>

  <body>
    {#  Fixed navbar #}
    <div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#nav-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>

          <a class="navbar-brand" href="http://www.blockcypher.com" title="live.blockcypher.com">
            <strong class="logo acc"></strong>
          </a>
        </div>

        <div class="collapse navbar-collapse" id="nav-collapse">

          <ul class="nav navbar-nav navbar-right">
            {% if not is_home %}
            <li>
              <form class="navbar-form navbar-search" role="search" method="post" action="{% url "home" %}">
                {% csrf_token %}
                <input type="hidden" value="{% firstof coin_symbol 'btc' %}" id="id_coin_symbol" name="coin_symbol">

                <div class="input-group">
                  <div class="input-group-btn">
                    <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                      <span id="search-dropdown-label">{% if coin_symbol %}{{ coin_symbol|coin_symbol_to_display_shortname }}{% else %}BTC{% endif %}</span> <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu" role="menu">
                      <li><a href="javascript:void(0);" onclick="setCoin('btc', 'BTC')">Bitcoin</a></li>
                      <li><a href="javascript:void(0);" onclick="setCoin('eth', 'ETH')">Ethereum</a></li>
                      <li><a href="javascript:void(0);" onclick="setCoin('ltc', 'LTC')">Litecoin</a></li>
                      <li><a href="javascript:void(0);" onclick="setCoin('doge', 'DOGE')">DogeCoin</a></li>
                      <li><a href="javascript:void(0);" onclick="setCoin('dash', 'DASH')">Dash</a></li>
                      <li><a href="javascript:void(0);" onclick="setCoin('bcy', 'BC Testnet')">BlockCypher Testnet</a></li>
                      <li><a href="javascript:void(0);" onclick="setCoin('btc-testnet', 'BTC Testnet')">Bitcoin Testnet</a></li>
                    </ul>
                  </div>
                  <input {% if not is_input_page %}autofocus="autofocus"{% endif %} name="search_string" id="id_search_string" type="text" class="form-control search-input" placeholder="Address, transaction or block">
                  <span class="input-group-btn">
                    <button type="submit" class="btn btn-primary" title="Search"><i class="fa fa-search"></i></button>
                  </span>
                </div>
              </form>
            </li>
            {% endif %}
            {% if coin_symbol %}
            <li class="hidden-sm">
              <a href="{% url 'coin_overview' coin_symbol %}" style="padding:7px 0 7px 15px;" title="{{ coin_symbol|coin_symbol_to_display_name }}">
               {% if coin_symbol == 'dash' %}<!-- This is done in order to works with previous css class "dash" already existing -->
                   <div class="header-coin dash-logo acc">{{ coin_symbol|coin_symbol_to_display_name }}</div>
               {% else %}
                   <div class="header-coin {{ coin_symbol }} acc">{{ coin_symbol|coin_symbol_to_display_name }}</div>
               {% endif %}
              </a>
            </li>
            {% endif %}
            <li class="dropdown hidden-sm">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                {% if not coin_symbol %}
                  Blockchains
                {% endif %}
                <span class="caret"></span>
              </a>
              <ul class="dropdown-menu" role="menu">
                <li>
                  <a href="{% url 'coin_overview' 'btc' %}">Bitcoin</a>
                </li>
                <li>
                  <a href="{% url 'coin_overview' 'btc-testnet' %}">Bitcoin Testnet</a>
                </li>
                <li>
                  <a href="{% url 'coin_overview' 'eth' %}">Ethereum</a>
                </li>
                <li>
                  <a href="{% url 'coin_overview' 'ltc' %}">Litecoin</a>
                </li>
                <li>
                  <a href="{% url 'coin_overview' 'doge' %}">Dogecoin</a>
                </li>
                <li>
                  <a href="{% url 'coin_overview' 'dash' %}">Dash</a>
                </li>
                <li>
                  <a href="{% url 'coin_overview' 'bcy' %}">BlockCypher Testnet</a>
                </li>
              </ul>
            </li>
            {% if user.is_authenticated %}
            <li class="dropdown {# hidden-sm #}">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                Account
                <span class="caret"></span>
              </a>
              <ul class="dropdown-menu" role="menu">
                <li>
                  <a href="{% url 'dashboard' %}">{% trans "Dashboard" %}</a>
                </li>
                <li>
                  <a href="{% url 'logout_request' %}">{% trans "Sign Out" %}</a>
                </li>
              </ul>
            </li>
            {% endif %}
            <li id="profile-menu" class="dropdown navbar-form">
              {% if tcp__ENABLE_TRANSLATIONS %}
                {% get_current_language as LANGUAGE_CODE %}
                {% get_language_info for LANGUAGE_CODE as lang %}
                <button class="dropdown-toggle btn-default btn" data-toggle="dropdown">
                  <strong>{{lang.name_local}}</strong> 
                  <b class="caret"></b>
                </button>
                <div class="dropdown-menu">
                  <form class="form-horizontal" action="{% url 'set_language' %}" method="post">
                    {% csrf_token %}
                    <input name="next" type="hidden" value="{{ redirect_to }}" />

                    <div class="switch-toggle well">
                    {% get_language_info_list for LANGUAGES as languages %}
                    {% for language in languages %}
                      <input id="{{ language.code }}" name="language" value="{{ language.code }}" type="radio" onclick="this.form.submit()"{% if language.code == LANGUAGE_CODE %} checked{% endif %}>
                      <label for="{{ language.code }}">
                        {{ language.name_local }}
                      </label>
                    {% endfor %}
                      <a class="btn btn-primary"></a>
                    </div>

                    <p>{% trans "Translations are currently in Beta."%}</p>
                  </form>
                  <div class="clearfix"></div>
                </div>
              {% endif %}
            </li>
          </ul>

        </div>
      </div>

    </div>

    {% if is_home %}
      <div class="main-container home">
        {# Including the messages for the homepage in the home template #}
    {% else %}
      <div class="main-container">
        {# Page Header Stuff #}
        <div class="page-header">
          <div class="container">
            {% block page_header %}
            {% endblock page_header %}
          </div>
        </div>
        {% include "partials/messages.html" %}
    {% endif %}

    {# page content here #}
    {% block content %}{% endblock content %}

    {% if coin_symbol == 'bcy' %}
      <div class="container">
        <p>
          Check out our
          <a href="https://www.blockcypher.com/dev/bitcoin/#testing{% if address %}?a={{ address }}{% endif %}">Blockcypher Faucet</a>
        </p>
      </div>
    {% endif %}

    {# end main-container #}
    </div>

    {# Footer #}

    <footer class="main-footer">
      <div class="container">
        <div class="row">

          <div class="col-sm-4">
            <p>We are social 
              <a href="https://twitter.com/blockcypher" class="social" target="_blank">
                <i class="fa fa-twitter"></i>
              </a> 
              <a href="https://www.facebook.com/blockcypher" class="social" target="_blank">
                <i class="fa fa-facebook"></i>
              </a> 
              <a href="https://github.com/blockcypher" class="social" target="_blank">
                <i class="fa fa-github-alt"></i>
              </a>
            </p>
          </div>

          <div class="col-sm-4 text-center">
          <p class="text-center reset">
            <a href="https://github.com/blockcypher/explorer" class="btn btn-default btn-lg btn-gh">
              <i class="fa fa-github"></i> 
              Fork me on GitHub
            </a>
          </p>
          </div>

          <div class="col-sm-4">
            <p class="text-right">
              Powered by <a href="http://www.blockcypher.com/">BlockCypher Web Services</a><br>
              © 2023 - BlockCypher
            </p>
          </div>

        </div>
      </div>
    </footer>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
    <script src="{% static "js/custom.js" %}"></script>

    {% block extra_js %}{% endblock extra_js %}
    {% include "partials/ga.html" %}
  </body>
</html>

templates/change_pw.html
{% extends "base.html" %}

{% load i18n %}
{% load static %}

{% block title %}{% trans "Change Password" %}{% endblock title %}

{% block page_header %}
  <h1>{% trans "Change Password" %}</h1>
{% endblock page_header %}

{% block content %}

<div class="form-page">
  <div class="container">
    <div class="row">
       <div class="col-md-4 col-md-offset-4">

        <div class="form-well">
          <form role="form" method="post" action="{% url "change_password" %}">
            {% load crispy_forms_tags %}
            {{ form|crispy }}
            {% csrf_token %}
            <p class="text-center">
              <button type="submit" class="btn btn-primary btn-lg btn-block">{% trans "Change Password" %}</button>
            </p>
          </form>

        </div>

      </div>
    </div>
  </div>
</div>

{% endblock content %}

templates/confirm_pw_reset.html
{% extends "base.html" %}

{% load i18n %}
{% load static %}

{% block title %}{% trans "Check Your Email" %}{% endblock title %}

{% block page_header %}
  <h1>{% trans "Check Your Email to Reset Your Password" %}</h1>
{% endblock page_header %}

{% block content %}

<div class="container">
  <div class="section">
    <div class="row">
      <p>
        Please check your email
        (<b>{{ user.email }}</b>)
        and click the link to confirm your subscription.
      </p>

      <p>
        <a class="btn btn-default" data-toggle="collapse" data-target="#viewdetails">Didn't get the email?</a>
      </p>
      <p class="collapse" id="viewdetails">
        Please wait one minute and then check your spam folder for a message from <b>notifications@blockcypher.com</b>.
        If it still hasn't arrived, please
        <a href="mailto:contact@blockcypher.com">contact us</a>
        so we can fix it.
        Sorry about that!
      </p>


    </div>
  </div>
</div>
</div>

{% endblock content %}

templates/pushtx.html
{% extends "base.html" %}

{% load i18n %}
{% load humanize %}
{% load btc_formats %}
{% load static %}

{% block title %}
  Push Raw {{ coin_symbol|coin_symbol_to_display_name }} Hexadecimal Transaction
{% endblock %}

{% block page_header %}
  <h1>
    <i class="fa fa-send"></i> 
    Broadcast Your Transaction
  </h1>
{% endblock page_header %}

{% block content %}

<div class="section">
  <div class="container">

    <form role="form" method="post" action="{% url 'push_tx' coin_symbol %}">
      {% load crispy_forms_tags %}
      {{ form|crispy }}
      {% csrf_token %}
      <p class="text-center">
        <button type="submit" class="btn btn-primary btn-lg">{% trans "Broadcast Transaction" %} </button>
      </p>
    </form>

    <p class="text-center">
      Not ready to broadcast?
      <a href="{% url 'decode_tx' coin_symbol %}">Click here</a>
      to decode a raw transaction without broadcasting.
    </p>

  </div>
</div>

{% endblock content %}

templates/received_widget.html
{% load btc_formats %}

<html>
  <head>
    <title></title>
    {# Bootstrap core CSS #}
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet">

    {# FontAwesome #}
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">

  </head>
  <body>
    <a target="_blank" href="{{ BASE_URL }}{% url 'address_overview' coin_symbol b58_address %}" class="btn btn-default">

      <i class="fa fa-qrcode"></i> 
      {{ b58_address }}

      <h4>
        {% satoshis_to_user_units_trimmed address_overview.total_received 'btc' coin_symbol True 0 %}
        Received
      </h4>

    </a>

    <p align="center">
      <a class="text-muted" href="http://www.blockcypher.com/">Powered by BlockCypher</a>
    </p>

  </body>
</html>

templates/reset_pw.html
{% extends "base.html" %}

{% load i18n %}
{% load static %}

{% block title %}{% trans "Set Password" %}{% endblock title %}

{% block page_header %}
  <h1>{% trans "Set Password" %}</h1>
{% endblock page_header %}

{% block content %}

<div class="form-page">
  <div class="container">
    <div class="row">
       <div class="col-md-4 col-md-offset-4">

        <div class="form-well">
          <form role="form" method="post" action="{% url "reset_pw" verif_code %}">
            {% load crispy_forms_tags %}
            {{ form|crispy }}
            {% csrf_token %}
            <p class="text-center">
              <button type="submit" class="btn btn-primary btn-lg btn-block">{% trans "Set Password" %}</button>
            </p>
          </form>

        </div>

      </div>
    </div>
  </div>
</div>

{% endblock content %}